name: chat
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^2.2.2
  pull_to_refresh: ^1.6.2
  provider: ^4.3.2+2
  http: ^0.12.2
  flutter_secure_storage: ^3.3.5

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/
